Repository cse110-fa22-group5/cse110-fa22-group5, pull requests merged in 2022-12, with the labels that each got.

#108 Finish unit testing for backend
  .eslintrc.json
  babel.config.json
  jest-puppeteer.config.js
  jestTesting/indexedDB.test.js
  package.json
  source/scripts/noteStorage.js
Labels: testing

#121 Feature/update title and back button confirm
  .eslintrc.json
  admin/cipipeline/phase2.md
  admin/meetings/11-29-22-checkin.md
  puppeteerTesting/dashboardE2E.test.js
  source/scripts/notesEditor.js
  specs/adrs/cicd.md
Labels: feature, frontend

#123 Testing/e2e updates
  babel.config.json
  jest-puppeteer.config.js
  jestTesting/indexedDB.test.js
  puppeteerTesting/dashboardE2E.test.js
Labels: testing

#125 Fix "Sort Notes by Last Modified"
  source/scripts/index.js
Labels: bug

#128 Feature/disable save button
  .github/workflows/main.yml
  README.md
  puppeteerTesting/dashboardE2E.test.js
  source/scripts/index.js
  source/scripts/notesEditor.js
Labels: bug, frontend
